// CANONICAL dispatch script — battle-tested authoring the foundation tier
// (AIE-100/101/102/103/104/110, 39 packets). Author every packet of ONE
// course, four-gate each, agents write files straight to disk.
//
// The process (see curriculum/ai-engineer/DISPATCH.md for the full contract):
//   1. Generate this course's COURSES entry:
//        node --experimental-strip-types curriculum/ai-engineer/dispatch/emit-course-snippet.ts AIE-201
//      Paste the output into the COURSES map below, and set SELECTED to
//      that course's code.
//   2. Invoke via Workflow({ scriptPath: "curriculum/ai-engineer/dispatch/dispatch-course.js" }).
//      No `args` — Workflow's args-threading is unreliable for this; the
//      course data is embedded (Workflow scripts have no filesystem access,
//      so they can't import curriculum.ts directly — emit-course-snippet.ts
//      is what keeps this embedding from drifting out of sync with it).
//   3. LESSON LEARNED THE HARD WAY: dispatch ONE course at a time. Running
//      four courses concurrently (16+ agents) hit a session token limit
//      partway through every one of them. One course (5-9 agent calls) is
//      the safe unit; wait for it to land before starting the next.
//   4. Read the gate results. Any packet with overallPass:false has a real,
//      specific defect (the gates are adversarial by design) — fix it with
//      a focused agent that reads the flagged file, applies exactly the
//      named fixes, and re-gates. finish-course.js in this directory
//      handles the case where a dispatch run authored some packets but
//      didn't finish gating all of them (background runs can stall).
//   5. Regenerate the runnable Course and rebuild:
//        node --experimental-strip-types src/generate-course-from-curriculum.ts
//        npm run build && npm test
export const meta = {
  name: 'dispatch-course-materials',
  description: 'Author and four-gate every module packet of one foundation course; agents write materials to disk',
  phases: [
    { title: 'Author', detail: 'one agent per packet writes full lesson material to disk' },
    { title: 'Gate', detail: 'four-gate review per packet: technical, eval-discipline, ethics, coherence' },
  ],
}

// ─────────── EDIT THIS PER RUN ───────────
const SELECTED = 'AIE-301'
// ─────────────────────────────────────────

const COURSES = {
  'AIE-301': {
    code: 'AIE-301', title: "Large Language Models: Pretraining to Post-Training", tier: 'specialization', durability: 'mixed',
    descentArc: "Descend to the byte: build the BPE tokenizer, then a small LM, then the post-training arc — SFT, preference optimization, RL — by hand on the corpus you built in AIE-203. Re-ascend able to fine-tune any open model with a reason and an eval proving the delta.",
    outpaces: "CS336's from-scratch depth without CS336's assumed background — the ramp is our own foundation tier. Post-training gets equal weight with pretraining (the industry reality no MOOC reflects), and the corpus comes from AIE-203, so the learner has provenance on every token their model saw.",
    ethicsThread: "Tier 1: whose preferences fill the reward signal is a design decision, documented in every lab's papers. Tier 2: what 'alignment' suppresses — aligned to whom is the entire contest, treated as settled. Tier 3: you are building the voice; the field cannot say what, if anything, is home. Proceed — but proceed knowing.",
    prereqNote: "Prereq AIE-202 (autograd from scratch through the transformer, then PyTorch fluency from M06 onward — the learner has already built and gradchecked a transformer block from the paper's equations) and AIE-203 (a hand-built, provenance-documented training/eval corpus with contamination discipline — THIS is the corpus this course trains on) and AIE-204 (eval design before systems, gold sets, LLM-as-judge validation, statistics — every build milestone here is graded with an eval, never a demo). This is the course where everything built in the core tier gets used for its actual purpose: the AIE-203 corpus stops being an exercise and becomes training data; the AIE-204 eval discipline stops being abstract and gates every milestone (tokenizer, pretrained LM, SFT, preference-tuned) before it counts as done. Toy-scale throughout (a small LM, not a frontier model) — the point is that every step from byte to aligned model was built and understood by hand, not that the model is good.",
    toolchain: "Python 3.12+, PyTorch (the AIE-202-M06 fluency layer, now doing real work), a byte-level/BPE tokenizer built from scratch before any library tokenizer is named, small-scale compute (CPU-feasible or a single small GPU — every lab states its actual wall-clock budget), Hugging Face transformers/peft/trl only AFTER the from-scratch equivalent is built and understood (current-tools sections clearly isolated per this course's 'mixed' durability), pytest. The AIE-203-authored corpus is the training data throughout — no external dataset substitutes for it.",
    packets: [
      { id: "AIE-301-M01", title: "Tokenization: BPE from scratch and its politics", hours: 16, focus: "Descend to the byte: build a BPE tokenizer completely from scratch (byte-pair merges computed by hand on a small corpus first, traced step by step, before scaling up), then run it on the AIE-203 corpus and confront its actual failure modes (whitespace handling, non-English/non-Latin scripts, digit splitting, the vocabulary-size trade-off). The 'politics' in the title is literal and assessed: whose text tokenizes efficiently and whose doesn't is a documented, citable inequity, not a footnote — tie directly to this course's ethics thread." },
      { id: "AIE-301-M02", title: "Pretraining a small LM on your own corpus", hours: 22, focus: "Pretrain a small LM end to end on the AIE-203 corpus, using the AIE-202-M05 transformer architecture (built from the paper's equations) now trained for real at small scale: data loading, a real training loop with checkpointing, loss curves that must be read and diagnosed (callback to AIE-202-M07's pathology clinic) not just watched go down. Predict what the loss curve and sample generations will look like at three checkpoints before running, and reconcile against what actually happens." },
      { id: "AIE-301-M03", title: "Scaling: what compute, data, and parameters buy", hours: 16, focus: "Scaling as an intuition the learner can compute, not a chart they're shown: derive and verify (at small scale, where it's checkable) what additional parameters, additional data, and additional compute each individually buy, using the learner's own M02 training runs as the empirical base — a scaling LAW is a claim about the world, and this module's certification artifact is a small-scale scaling study the learner ran and can defend, tying directly to AIE-204's honest-inference discipline (this is exactly the kind of extrapolation that AIE-204-M03 warned can be overclaimed)." },
      { id: "AIE-301-M04", title: "SFT: instruction tuning hands-on", hours: 18, focus: "SFT (instruction tuning) hands-on: take the M02 pretrained model and build an instruction-tuning pipeline from scratch on a small instruction dataset, with an AIE-204-style eval (not a vibes check) proving the delta between base and SFT'd model on held-out prompts. Predict which capabilities SFT will and won't add before measuring — a live rebuttal to the 'SFT teaches new knowledge' misconception." },
      { id: "AIE-301-M05", title: "Preference optimization: RLHF, DPO-family, reward hacking", hours: 20, focus: "Preference optimization built from the mechanics up: RLHF's reward-model-plus-RL pipeline traced by hand on a toy problem first, then a DPO-family method implemented from its actual loss function (not a library call) and run on a small preference dataset, with reward hacking DELIBERATELY induced and diagnosed (a reward model gamed on purpose, the exploit found the same way AIE-204-M02 taught gaming-resistance) before being fixed. This is the course's heaviest ethics load — tie directly to the course-level thread on whose preferences fill the reward signal." },
      { id: "AIE-301-M06", title: "Parameter-efficient fine-tuning: LoRA/QLoRA in anger", hours: 18, focus: "Parameter-efficient fine-tuning in anger: derive LoRA's low-rank decomposition from the actual linear-algebra argument (why a low-rank update is often sufficient, connecting back to AIE-201-M04's PCA/low-rank intuition), implement it from scratch on the M02/M04 model, THEN name what the Hugging Face peft library's LoRA/QLoRA adds on top (quantization mechanics, real memory/compute trade-offs measured, not asserted) — current-tools specifics isolated per durability discipline." },
      { id: "AIE-301-M07", title: "Reasoning and RL: test-time compute, verifiable rewards", hours: 18, focus: "Reasoning and RL at the current frontier of practice: test-time compute (why more inference-time computation can substitute for scale, demonstrated on a small verifiable-reward task, not just described) and a from-scratch-enough RL-with-verifiable-rewards loop (a task with a checkable correct answer, e.g. arithmetic or a small logic puzzle) run on the M02/M04 model, with the verification mechanism itself audited for gaming (can the model learn to exploit the verifier rather than solve the task — an AIE-204-style adversarial check made concrete)." },
      { id: "AIE-301-M08", title: "Open-weight ecosystem: licenses, model cards, sovereignty", hours: 12, focus: "The re-ascent: survey the open-weight ecosystem as a sovereignty question, not a shopping list — license terms actually read and compared (not summarized secondhand), model cards evaluated for what they disclose and what they don't (tie back to AIE-203's provenance/consent discipline), and a real fine-tune of an open model for a stated task with an AIE-204-grade eval proving the delta, as the course's certification artifact: 'fine-tune any open model with a reason and an eval proving the delta,' the course's own stated outcome, demonstrated for real." },
    ],
  },
  'AIE-204': {
    code: 'AIE-204', title: "Evaluation and Experimentation", tier: 'core', durability: 'durable',
    descentArc: "Descend beneath 'it seems to work' to what knowing would actually require: a gold set, a metric that resists gaming, a statistic that survives scrutiny. Build evals and validate the judge itself. Re-ascend carrying the discipline that gates every system you build after this.",
    outpaces: "Evaluation as a full course, positioned BEFORE the LLM tier — the single largest gap in every competitor. The 2025-26 industry lesson (evals are the core discipline of AI engineering) made structural: nothing in later courses ships without an eval, because the learners already know how to build one.",
    ethicsThread: "Tier 1: benchmark scores drive capital allocation; contamination is documented and widespread. Tier 2: what leaderboards suppress — the gap between measured task and claimed capability is where every overclaim lives. Tier 3: you will be asked to make an eval say yes; decide now what your number is not for sale for.",
    prereqNote: "Prereq AIE-201 (the evaluation discipline's roots: honest train/val/test splits, leakage, baselines that must be beaten, the whole M05/M06 failure catalog). Co-req AIE-203 (data engineering — not load-bearing for this course's own labs). This course is positioned deliberately BEFORE the LLM/generative tier (AIE-301+): the thesis is that a learner should know how to design an eval before they ever build the system it will judge. No new model-building here — every lab is about measurement: gold sets, metrics that resist gaming, statistics that survive scrutiny, and (starting M04) evaluating generative/LLM systems specifically, including building and VALIDATING an LLM-as-judge pipeline against real human-labeled disagreement — not just asserting the judge is good. M04's LLM-as-judge labs need an actual model call path; use a small, cheap, swappable model behind a thin interface (isolate the current-model specifics per the course's own durability-discipline convention) so the durable lesson (judge validation methodology) doesn't rot when the model changes.",
    toolchain: "Python 3.12+, pandas, scipy/statsmodels for the statistics modules (real power analysis, real significance tests — no hand-waved p-values), pytest, a thin LLM-client interface for M04's judge labs (swappable backend, current-model specifics isolated per durability discipline), matplotlib for distributions/power curves. No GPU training — this course measures systems, it doesn't build or train them.",
    packets: [
      { id: "AIE-204-M01", title: "Why evals precede systems", hours: 12, focus: "Descend to why 'it seems to work' is not knowledge: the module opens by handing the learner a system that LOOKS good on a demo and asking them to say, with evidence, whether it actually works — and watching them discover they can't, because no eval exists yet. Build the case, from first principles, for why an eval must be designed before the system it measures, tying directly back to AIE-201-M05's leakage/baseline discipline as the ancestor of everything in this course. This module sets the whole course's stance: an eval is a claim about the world, and claims need evidence." },
      { id: "AIE-204-M02", title: "Gold sets, metrics, and gaming resistance", hours: 18, focus: "Build a gold set by hand for a real task (labeling criteria, inter-annotator agreement measured not assumed, edge cases deliberately included) and a metric that resists gaming — hand the learner a metric, have them find the gaming exploit themselves (a degenerate output that scores perfectly), then fix the metric and prove the exploit no longer works. This is AI-PRIMM applied to measurement itself: predict the gaming vector before being shown it." },
      { id: "AIE-204-M03", title: "Experiment statistics: power, significance, honest inference", hours: 18, focus: "Descend into the actual statistics of experimentation: power analysis (compute the sample size a real experiment needs, by hand, before running it), significance testing done honestly (multiple-comparisons correction, why p-hacking works and how to close it), and regression to the mean demonstrated live on a dataset engineered to produce it. The certification artifact is a statistics clinic: find the specific, named flaw in a real published experiment design, not a generic checklist." },
      { id: "AIE-204-M04", title: "Evaluating generative systems: rubrics, pairwise, LLM-as-judge", hours: 20, focus: "Evaluating generative systems specifically: rubric-based grading, pairwise comparison (and why pairwise resists a scoring bias that absolute rubrics don't), and building an LLM-as-judge pipeline from scratch — then the module's real payoff: VALIDATE the judge against real human-labeled disagreement data, measure agreement rate, and characterize exactly where and why the judge and the humans diverge. A judge that is merely built and never validated fails this module's whole premise." },
      { id: "AIE-204-M05", title: "Contamination, Goodharting, and benchmark forensics", hours: 16, focus: "Benchmark forensics as a hands-on investigation: detect contamination in a provided eval set (a held-out set that turns out to overlap training data — find the overlap yourself, don't be told it exists), and Goodharting demonstrated live (optimize hard against a metric on a toy system and watch the metric rise while the real capability it was supposed to measure doesn't, or gets worse). Connects directly to this course's own ethics thread: leaderboards suppress the gap between measured task and claimed capability." },
      { id: "AIE-204-M06", title: "Error analysis as a practice: reading transcripts, taxonomy building", hours: 16, focus: "Error analysis as a practice, not an afterthought: read a large batch of real transcripts/outputs from a provided (flawed) system, build an error taxonomy FROM the data (not from a template handed down), and quantify which error categories actually drive the metric's shortfall — the certification artifact is a taxonomy a second reader could apply consistently, tying back to M02's inter-annotator-agreement discipline." },
      { id: "AIE-204-M07", title: "The eval report: writing for a skeptic", hours: 10, focus: "The re-ascent and the course's payoff: write an eval report for a genuinely skeptical reader — someone financially or politically motivated to find a hole in the claim. The report must state the eval's own limitations, the confidence level, and what would change the conclusion, modeled directly on the 'defensible judgment trail' standard the whole curriculum has been building toward. Graded on whether a skeptic actually signs it, not on polish." },
    ],
  },
  'AIE-203': {
    code: 'AIE-203', title: "Data Engineering for AI", tier: 'core', durability: 'mixed',
    descentArc: "Descend from 'the dataset' to the record, the byte on disk, the provenance of every row. Build a corpus by hand — dedup, filter, contamination-check, consent posture. Re-ascend able to stand behind every token a model of yours will ever see.",
    outpaces: "The corpus-construction module is the differentiator: no curriculum teaches building a training corpus with provenance, contamination discipline, and consent posture — the exact skill the LLM era actually runs on. Pipelines are graded on failure behavior (replays, duplicates, out-of-order), not happy paths.",
    ethicsThread: "Tier 1: every record was an event in someone's life; scraping's legal status is actively contested. Tier 2: what 'publicly available' suppresses — availability was never consent. Tier 3: your corpus contains someone who would object; you can't identify them; you train anyway or you don't — decide and write down why.",
    prereqNote: "Prereq AIE-101 (Python fluency, real toolchain — testing, packaging, debugging discipline) and AIE-110 (data structures/scale — the learner already reasons about complexity budgets and can build an index or a cache by hand). Co-req none, but runs alongside AIE-202 in the core tier. This course is NOT about ML — no models are trained here. It is the plumbing every later course assumes exists: a queryable warehouse, pipelines that survive replays and out-of-order data, and — its differentiator — a training/eval corpus built by hand with documented provenance, dedup, filtering, and a written consent posture. AIE-301 (the RAG/retrieval course) directly reuses this course's corpus-construction artifact, so M05 in particular must produce something concrete and reusable, not a toy.",
    toolchain: "Python 3.12+, SQLite/PostgreSQL (SQL fluency built on a real engine, not a toy in-memory table), pandas for batch work, a lightweight orchestrator built by hand first (a DAG-runner in ~200 lines) before naming what Airflow/Dagster add, a minimal streaming harness (a Python generator/queue-based simulation of a log — no Kafka cluster required, but the exactly-once/at-least-once semantics must be real, not hand-waved), pytest, and standard corpus tooling (regex/hash-based dedup, a real contamination-check script run against a held-out set). No GPUs needed.",
    packets: [
      { id: "AIE-203-M01", title: "SQL and data modeling to fluency", hours: 18, focus: "Descend from 'query the database' to relational modeling as a discipline: normalization and when to deliberately break it, indexes as a concrete trade (build one by hand on a large table, measure the query-plan difference before and after), and SQL fluency exercised against a real engine (SQLite or Postgres, not an in-memory toy) with schemas that have to survive being asked questions nobody designed them for. Predict what an unindexed query plan will do before running EXPLAIN and finding out." },
      { id: "AIE-203-M02", title: "Batch pipelines: ETL, idempotency, orchestration", hours: 16, focus: "Build a batch ETL pipeline from raw scripts first (so every failure mode is visible and hand-traceable), then introduce idempotency as a property you must design for, not get for free — replay the same batch twice on purpose and watch a naive pipeline corrupt itself before fixing it. Build a minimal DAG-runner (~200 lines) before naming what a real orchestrator (Airflow/Dagster) adds on top. Grading is on failure behavior (replays, partial failures, out-of-order arrival), never on a clean happy-path demo." },
      { id: "AIE-203-M03", title: "Streaming: logs, exactly-once illusions, real-time ingestion", hours: 16, focus: "Descend into what 'real-time' actually means: logs as the substrate, at-least-once vs exactly-once as a genuinely hard distributed-systems problem (not a checkbox), and a hand-built streaming simulation (Python generator/queue, not a Kafka cluster) that makes the learner produce a duplicate or an out-of-order event on purpose and handle it. The 'exactly-once illusion' in the module title is the lesson: name precisely what mechanism (idempotency keys, dedup windows) is doing the actual work when a system claims exactly-once." },
      { id: "AIE-203-M04", title: "Data quality engineering: expectations, lineage, monitoring", hours: 14, focus: "Data quality as an engineering discipline with the same rigor as testing code: write data expectations (schema, range, null-rate, referential) as executable checks, not documentation; build a minimal lineage tracker that answers 'which raw source produced this row' after several pipeline hops; and instrument monitoring that catches a silent quality regression (a source schema drift, a null-rate spike) before it reaches a downstream consumer. Predict which of several planted data-quality bugs each check will and won't catch, before running them." },
      { id: "AIE-203-M05", title: "Corpus construction: provenance, dedup, filtering, contamination", hours: 22, focus: "The course's differentiator and its most consequential module: construct an actual training/eval corpus from raw sources by hand — deduplication (exact and near-duplicate, e.g. minhash/simhash), filtering (quality heuristics, language ID, toxicity/PII screens with documented false-positive/negative trade-offs), a real contamination check against a held-out eval set (not just an assertion that one was run), and a written provenance record and consent posture for every source. This corpus artifact is directly reused by AIE-301, so it must be a real, documented, defensible deliverable — graded on the written judgment trail (what was excluded and why), not on corpus size." },
      { id: "AIE-203-M06", title: "Storage economics: formats, lakes, warehouses, cost", hours: 14, focus: "Storage economics as a durable-core lesson wrapped around a swappable-surface subject: the actual trade-offs between row vs. columnar formats (build a small benchmark showing why Parquet beats CSV for the analytic queries this course has been running), what a data lake vs. a warehouse is actually optimizing for, and a real cost model (bytes scanned, storage tier, query frequency) the learner computes by hand for a given workload before naming which current vendor/tool fits it — with the current-tools specifics isolated into a clearly marked section per the course's 'mixed' durability rating." },
    ],
  },
  'AIE-202': {
    code: 'AIE-202', title: "Deep Learning: Autograd to Transformers", tier: 'core', durability: 'durable',
    descentArc: "Descend to raw arrays and build an autograd engine — the chain rule you derived in AIE-103, now as a machine you wrote. Build up through CNN, RNN, transformer, each earned from scratch. Re-ascend fluent in PyTorch, wielding it as an instrument whose every abstraction you could rebuild.",
    outpaces: "The Karpathy build-it-yourself ethos with what Zero-to-Hero lacks: assessment, ablation discipline, debugging drills on deliberately broken training runs, and a straight line into the LLM and production courses. Every architecture is earned by building, then made fluent in PyTorch.",
    ethicsThread: "Tier 1: scaling results replicate; interpretability lags capability, documented by the field itself. Tier 2: what 'we understand the architecture' suppresses — architecture is not behavior; builders ship systems whose specific capabilities surprise them. Tier 3: where does your responsibility end — at what you built, or at what it learned?",
    prereqNote: "Prereq AIE-201 (ML from first principles — the learning problem, gradient descent by hand, the evaluation contract, the failure catalog, all internalized). Co-req AIE-203 (data engineering — not load-bearing for this course's own labs, but running in parallel). Learners have derived gradients by hand (AIE-103) and built linear/logistic regression via hand-rolled gradient descent (AIE-201-M02), but have NEVER built an autograd engine, a neural net, or trained anything with more than one layer. This is the flagship descent-and-build course of the whole curriculum: everything is built from raw NumPy arrays FIRST (autograd, then every architecture), and PyTorch arrives only in M06, as a fluency layer over mechanics already fully understood — never as the starting point.",
    toolchain: "Python 3.12+, NumPy for M01-M05 (autograd through the transformer — all built from raw arrays), PyTorch from M06 onward, matplotlib for loss curves, pytest. GPU access is helpful but not required for the from-scratch modules (small toy models); PyTorch modules assume at least a laptop CPU, GPU optional with a documented CPU fallback.",
    packets: [
      { id: "AIE-202-M01", title: "Autograd from scratch: the tape and the chain rule", hours: 18, focus: "Descend to raw NumPy arrays and build a real autograd engine from scratch: a Value/Tensor class with a computation-graph tape, .backward() implementing reverse-mode automatic differentiation via the chain rule the learner already derived by hand in AIE-103-M03. Verify every gradient against manual finite-difference checks (gradcheck) before trusting a single backward pass. This module is the hinge of the whole course: every later architecture (M02-M08) is built ON this engine, not on PyTorch, until M06." },
      { id: "AIE-202-M02", title: "Training dynamics: init, normalization, optimizers, schedules", hours: 20, focus: "Train real (tiny) networks on the M01 engine and confront why training is hard: weight initialization (and why naive init explodes/vanishes, demonstrated by deliberately breaking it), batch/layer normalization (built from scratch, not imported), optimizers beyond vanilla SGD (momentum, Adam — derived and implemented, not just named), and learning-rate schedules. Every fix is demonstrated as a fix: show the broken training curve first, apply the technique, show it recover." },
      { id: "AIE-202-M03", title: "CNNs and representation learning", hours: 18, focus: "Build a CNN from scratch on the M01 engine: convolution as a specific weight-sharing pattern (not a mysterious operator — implement it as an explicit sliding-window matrix operation first, THEN as the optimized im2col/conv routine), pooling, and what representation learning actually means (visualize learned filters on a small trained model). Connect back to AIE-201-M04's PCA — both are ways of finding structure, one linear, one learned and nonlinear." },
      { id: "AIE-202-M04", title: "Sequences: RNNs to attention", hours: 18, focus: "Build an RNN from scratch (the recurrence as an explicit unrolled loop over the M01 engine, watch vanishing gradients happen live on a long sequence), then motivate attention as the SOLUTION to exactly that vanishing-gradient problem — build a minimal attention mechanism from scratch before any 'transformer' vocabulary appears. The descent here is temporal: from a sequential bottleneck to parallel attention, and the learner should feel why the field made that move, not just be told it happened." },
      { id: "AIE-202-M05", title: "The transformer, from the paper", hours: 22, focus: "The capstone build: implement the full transformer block from the original paper's actual equations — multi-head self-attention, positional encoding, layer norm placement, the feed-forward sublayer — on the M01 engine, then verify it reproduces expected shapes and gradient flow on a toy sequence task. This is AIE-102-M03's quality bar applied to the hardest architecture in the curriculum: nothing is imported, every equation in the paper becomes a line of code the learner wrote and can explain." },
      { id: "AIE-202-M06", title: "PyTorch fluency and the modern stack", hours: 18, focus: "The re-ascent begins: rebuild M01-M05's architectures in idiomatic PyTorch (nn.Module, autograd, DataLoader) and show that PyTorch's abstractions are now simply faster versions of exactly the mechanics already built by hand — never a new mystery. Benchmark hand-rolled vs PyTorch on the same toy task to make the 'PyTorch is just fast infrastructure over what you understand' claim measurable, not asserted." },
      { id: "AIE-202-M07", title: "Debugging training: the pathology clinic", hours: 20, focus: "The pathology clinic: hand the learner a training run that is broken in one of several specific, realistic ways (exploding loss, a silent data bug, a frozen-gradient layer, a normalization mistake) and have them diagnose it from the loss curve, gradient norms, and activation statistics ALONE — before being shown the code. This is debugging as a first-class skill, built the same way AIE-100/AIE-101's debugging modules were: reproduce, isolate, hypothesize, verify, on someone else's (deliberately broken) training run." },
      { id: "AIE-202-M08", title: "Ablation and attribution", hours: 16, focus: "Ablation and attribution as the course's evaluation discipline (callback to AIE-201-M05/M06 and forward to AIE-204): given a trained model, systematically remove/vary one component at a time (an attention head, a normalization layer, a skip connection) and attribute the performance change to that component with a defensible experiment design — not vibes. The certification artifact is a written ablation study a skeptical reader would trust." },
    ],
  },
  'AIE-201': {
    code: 'AIE-201', title: "Machine Learning from First Principles", tier: 'core', durability: 'durable',
    descentArc: "Descend beneath sklearn: implement regression, trees, k-means, PCA from scratch until the library is just a fast version of what you already understand. Build the failure catalog by hand — leakage, drift, the lying average. Re-ascend able to say, with evidence, when NOT to use ML at all.",
    outpaces: "Every algorithm is built from scratch and validated against scikit-learn, so nothing is incantation; the failure catalog (leakage, drift, Simpson's paradox, base-rate neglect) gets equal billing with the methods; 'when not to use ML' is an assessed outcome, which no competitor dares grade.",
    ethicsThread: "Tier 1: labeled data is bought labor; benchmark gains are measurable. Tier 2: what 'accuracy' suppresses — the distribution of error across people, and the labels' embedded worldview. Tier 3: your model's average hides a tail; name who lives there before you ship.",
    prereqNote: "Prereq AIE-103 (math as instruments — gradients, optimization, probability, information theory all built and hand-derived) and AIE-110 (data structures/scale — top-k, complexity budgets). Learners can derive a gradient by hand, compute in NumPy, and reason about algorithmic cost, but have never trained a model. This is the first ML course: no deep learning yet (AIE-202), no neural nets. Every algorithm here is built from raw NumPy first, THEN matched against scikit-learn to prove it's not incantation — sklearn is a late-arriving check, never the starting point.",
    toolchain: "Python 3.12+, NumPy, pandas, scikit-learn (comparison/verification only, never the primary implementation), pytest, matplotlib. No GPUs, no deep learning frameworks — those wait for AIE-202.",
    packets: [
      { id: 'AIE-201-M01', title: "The learning problem: generalization, capacity, the bet", hours: 14, focus: "Descend beneath 'the model learns' to what learning actually IS: a bet that the training set resembles the world, made precise via generalization, capacity, bias-variance, and the no-free-lunch reality. Build the first learning curve by hand (train/val error vs. model complexity) and watch overfitting happen live on a toy problem before any named algorithm exists. This module sets the whole course's stance: every later algorithm is just a different way of making this same bet." },
      { id: 'AIE-201-M02', title: "Linear models and regularization from scratch", hours: 18, focus: "Build linear and logistic regression from raw NumPy: closed-form OLS, then gradient descent (callback to AIE-103-M06), then regularization (L1/L2) as a literal penalty term added to the loss, watched live via coefficient paths as the penalty strength moves. Match every result against sklearn's LinearRegression/Ridge/Lasso to the same tolerance the earlier courses used for their reference implementations. Predict which regularization kills which coefficients before running." },
      { id: 'AIE-201-M03', title: "Trees, forests, and boosting from scratch", hours: 18, focus: "Build a decision tree from scratch (recursive splitting on information gain / Gini, by hand-computed on a tiny dataset first), then bagging (random forest) and boosting (gradient boosting) as compositions of that one tree. The descent is literal: from one hand-traceable split to an ensemble, built up piece by piece, never imported whole. Match against sklearn's RandomForestClassifier/GradientBoostingClassifier. Predict which ensemble handles a specific messy dataset (missing values, outliers) better, and why, before measuring." },
      { id: 'AIE-201-M04', title: "Unsupervised: clustering, PCA, embeddings", hours: 16, focus: "Build k-means (Lloyd's algorithm, from scratch, watch it converge on a 2D toy set you can plot) and PCA (via the eigendecomposition/SVD machinery from AIE-103-M02, not a library call) from raw NumPy. Connect PCA's low-rank approximation directly to what an 'embedding' will mean starting in AIE-202/AIE-301 — this module is where that word stops being a black box. Predict how many components explain 95% of variance before computing the scree plot." },
      { id: 'AIE-201-M05', title: "The evaluation contract: splits, leakage, baselines", hours: 18, focus: "The single most load-bearing module in the course: leakage, honest train/val/test splits, cross-validation, and baselines that must be beaten before any claim of 'it works' is credible. Build a leakage bug into a pipeline on purpose (e.g. scaling before splitting, target leakage via a proxy column) and have the learner FIND it from suspiciously good numbers alone — that's the certification artifact, not a passing script. This is the module every later evaluation discipline (AIE-204) assumes was internalized here first." },
      { id: 'AIE-201-M06', title: "The failure catalog: how ML lies", hours: 16, focus: "The failure catalog, hands-on: Simpson's paradox reproduced on real aggregated data, base-rate neglect demonstrated with a concrete confusion-matrix example, distribution shift simulated by training on one slice and testing on a deliberately different one, and the specific ways an accuracy number lies about a rare-class problem. Each failure mode gets a lab where the learner is handed a model that LOOKS good and must find the lie using only the data, before being told what's wrong." },
      { id: 'AIE-201-M07', title: "Feature engineering and the tabular endgame", hours: 14, focus: "Feature engineering as the actual day-to-day work of tabular ML: encoding categoricals (and why one-hot vs target-encoding is a leakage risk, tying back to M05), handling missing data honestly (not just dropna), feature interactions, and why gradient-boosted trees on well-engineered tabular features still beat deep learning on most real tabular problems — a fact the course states and defends with a real benchmark comparison, not received wisdom." },
      { id: 'AIE-201-M08', title: "When not to use ML", hours: 16, focus: "The course's payoff and its most unusual assessed outcome: given a real business problem, argue — with evidence, not vibes — that ML is the WRONG tool (a rule-based system, a lookup table, or 'don't build it' is better), or that it's the right tool but a much simpler model than the fancy one suffices. Graded on the argument's rigor, not on which answer was reached. This is the module that makes the whole course honest about when NOT to reach for the hammer everyone assumes you want." },
    ],
  },
  'AIE-100': {
    code: 'AIE-100', title: 'Working With AI Without Outsourcing Judgment', tier: 'foundation', durability: 'durable',
    descentArc: 'Descend beneath the illusion that generated code you can run is code you understand. Build the judgment instruments — prediction, tracing, verification — by hand on tiny artifacts. Re-ascend able to direct any AI coder while holding the responsibility it cannot.',
    outpaces: 'No mainstream curriculum teaches verification before generation. This is the program’s front door: the stance every later course assumes. The certification artifact is the judgment trail — the spec, the read, the caught error — never a program that runs.',
    ethicsThread: 'Tier 1: what code assistants verifiably do and whose labor trained them. Tier 2: what ‘productivity’ framing suppresses — the transfer of understanding away from the person responsible. Tier 3: when the code fails in production, what exactly did you own?',
    prereqNote: 'NO prior coding assumed — this is the entry point. Learners do NOT know C yet (that is AIE-102) and are only beginning Python (AIE-101 is a co-requisite). All labs use Python read at a beginner level, or pseudocode. The skill taught is directing, reading, and verifying AI-written code — not writing it fluently.',
    toolchain: 'Python 3.12+ read at beginner level; an AI coding assistant (any) as the thing being directed and verified; pytest for the verification labs.',
    packets: [
      { id: 'AIE-100-M01', title: 'The competence trap and the loop', hours: 8, focus: 'Name the competence trap on day one: AI output raises apparent capability faster than actual understanding, invisibly, because the code runs. Introduce AI-PRIMM (Predict, Prompt, Read, Verify, Integrate) and make Prediction-before-Prompting a hard habit. Light on code, heavy on the stance; sets the constitution for the whole program.' },
      { id: 'AIE-100-M02', title: 'Reading code you didn’t write', hours: 12, focus: 'The core skill: read unfamiliar (AI-generated) code line by line and say what it does before running it. Hand-tracing, predicting output, building an accurate mental model of someone else’s code. Assessed as hard as writing. Beginner Python artifacts.' },
      { id: 'AIE-100-M03', title: 'Specification as the decidable contract', hours: 10, focus: 'Turn intent into a specification precise enough that correctness is decidable. Ambiguity is the lesson — the AI does exactly what an ambiguous spec permits. Learners write specs, watch the AI satisfy them in unintended ways, and tighten. The spec becomes the thing you own.' },
      { id: 'AIE-100-M04', title: 'Verification instruments: traces, assertions, tests', hours: 14, focus: '‘It ran without error’ is never verification. Build the discriminating checks: hand-traces, assertions, and the first real tests (pytest). Every AI-generated artifact from here ships with a check that could have failed. The heaviest lab-based module of the course.' },
      { id: 'AIE-100-M05', title: 'Debugging generated code', hours: 10, focus: 'Reproduce, isolate, hypothesize, verify — on code you didn’t write and don’t fully understand. Debugging as the moment fundamentals arrive as instruments (a bug requires you to learn the concept to fix it). Beginner Python bugs with planted defects.' },
      { id: 'AIE-100-M06', title: 'Ownership, provenance, licensing', hours: 6, focus: 'Accepting the outcome regardless of who or what produced the artifact. Provenance of AI-generated code, licensing and training-data questions, what it means to sign your name to code a model wrote. Ethics of ownership made concrete. Lighter; closes the course.' },
    ],
  },
  'AIE-101': {
    code: 'AIE-101', title: 'Python and Software Craft', tier: 'foundation', durability: 'durable',
    descentArc: 'Descend from ‘it works’ to why: read the machine’s behavior in small programs before writing large ones, and prove every claim with a test. Build a real toolkit by hand. Re-ascend fluent, with tests as the instrument you reach for first, not last.',
    outpaces: 'Codebase-reading is assessed as hard as writing (no one else does this); testing taught from week one as the primary verification instrument, not a later chapter; every lab is a real artifact in the learner’s growing published toolkit repo.',
    ethicsThread: 'Tier 1: open source runs the world and is maintained by unpaid labor. Tier 2: what ‘community’ framing suppresses — extraction without contribution as the industry norm. Tier 3: your toolkit depends on maintainers you’ll never thank; what do you owe the commons you build on?',
    prereqNote: 'Prereq AIE-100 (the AI-PRIMM verification stance and reading discipline). Co-req with AIE-103 (math). Learners can read beginner Python and verify AI code; this course makes them fluent WRITERS. No C yet (AIE-102). Every lab is a real artifact committed to a published, CI-green toolkit package the learner maintains across the whole course.',
    toolchain: 'Python 3.12+, pytest (and property-based tests via hypothesis), git, a CI provider (GitHub Actions), packaging (pyproject/uv or pip).',
    packets: [
      { id: 'AIE-101-M01', title: 'The interpreter, values, names, and state', hours: 14, focus: 'What a Python program actually is: the interpreter, objects, names as bindings (callback to AIE-100’s aliasing), mutability, and state as the thing that makes programs hard. Predict-before-run on aliasing and mutation. Build the first toolkit module.' },
      { id: 'AIE-101-M02', title: 'Functions, data, and the standard library', hours: 16, focus: 'Functions as contracts, the core data structures (list/dict/set/tuple) and when each is right, iterators/generators, comprehensions, and the standard library as a toolbox to read before reaching for pip. Real toolkit functions with tests.' },
      { id: 'AIE-101-M03', title: 'Classes, protocols, and typing', hours: 16, focus: 'Classes, dunder methods, protocols/duck typing, and type hints as a machine-checked contract (mypy/pyright). Predict shape/type errors before running. When a class is right and when a function is enough.' },
      { id: 'AIE-101-M04', title: 'Testing as a way of thinking (pytest, property tests)', hours: 16, focus: 'Testing as the primary verification instrument, not a chore: pytest fluency, fixtures, parametrization, and property-based testing (hypothesis) — tests that find the inputs you didn’t think of. Tests written before or alongside code, always.' },
      { id: 'AIE-101-M05', title: 'Git, review, and collaborative craft', hours: 12, focus: 'Git fluency beyond commit/push: branching, rebase, resolving conflicts, reading history, and the review workflow (PRs, giving and taking review). Collaboration as a craft. The toolkit repo gets real branches and PRs.' },
      { id: 'AIE-101-M06', title: 'Errors, logging, debugging, profiling', hours: 16, focus: 'Errors and exceptions done right, structured logging, debugging with a debugger (not print), and profiling to fix slowness by measurement, not guessing. Given a slow/broken toolkit function, diagnose and fix with evidence.' },
      { id: 'AIE-101-M07', title: 'Packaging, environments, CI', hours: 14, focus: 'Reproducible environments, packaging the toolkit as a real installable, and wiring CI so tests run on every push. The learner ships a published, CI-green package. Predict what breaks a build before it breaks.' },
      { id: 'AIE-101-M08', title: 'Reading real codebases', hours: 16, focus: 'The capstone skill: read a 2,000-line unfamiliar real open-source repo and produce an accurate structural map in under two hours. Assessed as hard as writing. Timed structural-map exam on an unseen repo.' },
    ],
  },
  'AIE-103': {
    code: 'AIE-103', title: 'Mathematics for AI, Taught as Instruments', tier: 'foundation', durability: 'durable',
    descentArc: 'Descend from the symbol to the raw computation it compresses: compute the gradient, the projection, the expectation by hand and in NumPy before trusting the notation. Build each concept as a working operation. Re-ascend able to read a paper’s math as instruments, seeing exactly what each equation buys.',
    outpaces: 'Math arrives exactly when a real problem needs it (a shape error, an exploding loss, a misread benchmark) — never as prerequisite lectures. Every concept is taught twice: once in symbols, once in NumPy, and assessed by PREDICTING real numerical behavior, then measuring.',
    ethicsThread: 'Tier 1: mathematical results are the least contestable knowledge in the stack. Tier 2: what mathematical dressing suppresses — an equation lends false authority to whatever assumptions were fed into it. Tier 3: which number in your model’s report would you least like an auditor to ask you to derive?',
    prereqNote: 'Prereq AIE-100. Co-req with AIE-101 (Python). Learners can read/write beginner-to-intermediate Python and use NumPy. Every concept is taught in symbols AND in NumPy; labs predict numerical behavior then measure. No ML yet — this is the instrument-building that AIE-201/202 will wield.',
    toolchain: 'Python 3.12+, NumPy, matplotlib for seeing; pytest for the prediction-vs-measurement labs. By-hand derivation on paper is a graded artifact.',
    packets: [
      { id: 'AIE-103-M01', title: 'Linear algebra I: vectors, matrices, shape discipline', hours: 18, focus: 'Vectors and matrices as data and as operations; shape as a contract you predict before running (the shape error before it happens). Matrix-vector and matrix-matrix products by hand and in NumPy. Broadcasting rules. This is the module that ends shape-error confusion forever.' },
      { id: 'AIE-103-M02', title: 'Linear algebra II: decompositions, projections, embeddings', hours: 16, focus: 'Dot products as similarity, projections, norms, eigen/SVD intuition, and why embeddings are vectors in a learned space. Compute a projection and a low-rank approximation by hand and in NumPy. Connect to what AIE-201/301 will call embeddings.' },
      { id: 'AIE-103-M03', title: 'Calculus and gradients: the chain rule as an engine', hours: 18, focus: 'Derivatives as sensitivity, the gradient as a direction, and the chain rule as the engine backprop will automate (forward reference to AIE-202’s autograd). Take gradients of small compositions by hand, verify numerically. Predict which way a loss moves.' },
      { id: 'AIE-103-M04', title: 'Probability: uncertainty stated honestly', hours: 18, focus: 'Distributions, expectation, variance, conditional probability, Bayes, and likelihood. Uncertainty as something you state, not hide. Simulate to check every analytic claim. Predict a distribution’s behavior, then sample and measure.' },
      { id: 'AIE-103-M05', title: 'Statistics: estimation, intervals, and the lies of averages', hours: 16, focus: 'Estimation, confidence intervals, hypothesis testing done honestly, and the specific ways averages and samples lie (Simpson’s paradox, survivorship, base rates). This is the statistical honesty AIE-204 will make a full discipline. Find the lie in a real chart.' },
      { id: 'AIE-103-M06', title: 'Optimization: loss landscapes, SGD, convergence intuition', hours: 18, focus: 'Loss landscapes, gradient descent and SGD, learning rate, convexity vs the reality of deep-net landscapes, and convergence intuition. Implement gradient descent from scratch, watch it converge/diverge, predict the effect of a learning-rate change before running.' },
      { id: 'AIE-103-M07', title: 'Information theory: entropy, cross-entropy, KL as distance', hours: 16, focus: 'Entropy, cross-entropy (the loss AIE-202 will train with), and KL divergence as a directed distance between distributions. Compute each by hand and in NumPy. Why cross-entropy is THE classification loss. Predict which distribution has higher entropy, then compute.' },
    ],
  },
  'AIE-104': {
    code: 'AIE-104', title: 'The Machine at Scale: Linux, Networks, Concurrency, Containers', tier: 'foundation', durability: 'durable',
    descentArc: 'Descend from ‘the server handles it’ to the socket, the process, the shared byte two threads fight over. Build a service from those parts. Re-ascend able to reason about a running system’s failure modes instead of trusting its abstractions.',
    outpaces: 'The operational half of the machine, taught right after the C descent so concurrency lands on top of real memory understanding, not before it. Every concept is exercised on real systems; the container is opened up, not invoked.',
    ethicsThread: 'Tier 1: the systems that scale are the systems designed to operate without knowing their users individually. Tier 2: what ‘scale’ suppresses — scale is a decision about relationship, not just throughput. Tier 3: the service you just built holds strangers’ data; what do you owe them that no container enforces?',
    prereqNote: 'Prereq AIE-102 (C, the memory hierarchy, the GIL). Learners know C, pointers, processes-vs-threads at the memory level, and Python. This course adds the OS/network/concurrency/container layer ON TOP of that metal understanding — e.g. the GIL from AIE-102 explains why Python parallelism is process-level.',
    toolchain: 'Linux shell (bash), C and Python for the socket/concurrency labs, Docker for containers, standard tools (curl, ss/netstat, strace/ltrace where useful). Real machines, measured.',
    packets: [
      { id: 'AIE-104-M01', title: 'Linux, the shell, processes, and signals', hours: 14, focus: 'The OS as the thing running your program: the shell, processes and the process tree, file descriptors, permissions, and signals. Write shell that composes real tools; send and handle a signal. Predict what a pipeline does before running it.' },
      { id: 'AIE-104-M02', title: 'Networking and APIs from the wire up', hours: 16, focus: 'Networking from the socket up: TCP, HTTP as text on a wire, TLS, DNS, latency vs bandwidth. Write a tiny socket server and client in C and/or Python, then an HTTP handler. Predict round-trip behavior; read a real request/response by hand.' },
      { id: 'AIE-104-M03', title: 'Concurrency, parallelism, and shared state', hours: 16, focus: 'Concurrency vs parallelism, threads vs processes, the shared-mutable-state hazard (callback to AIE-102’s non-atomic increment and the GIL), locks, and why Python parallelism is process-level. Build a program with a real race, then fix it. Predict the race before you see it.' },
      { id: 'AIE-104-M04', title: 'Containers and reproducible environments, opened up', hours: 14, focus: 'What a container actually IS (namespaces + cgroups over one kernel, not a VM), images and layers, and reproducibility. Build and inspect a container from a Dockerfile; open it up to see the process from the host. Predict image size and what a layer caches.' },
      { id: 'AIE-104-M05', title: 'Putting it together: a measured, containerized service', hours: 10, focus: 'Capstone: containerize a small service, put it under load, and measure its real resource envelope (latency, memory, CPU) and failure behavior. Predict the SLO before load-testing; explain where it breaks and why in the terms of M01–M04.' },
    ],
  },
  'AIE-110': {
    code: 'AIE-110', title: 'Data Structures, Algorithms, and Scale', tier: 'foundation', durability: 'durable',
    descentArc: 'Descend beneath the library call to the structure doing the work, and watch it break at 10^9 items. Build the structures AI leans on — the ANN index, the streaming counter — by hand. Re-ascend choosing data structures by measured cost, not habit.',
    outpaces: 'Ruthlessly scoped to what AI systems use — vector search, top-k, streaming aggregation, graph algorithms — with every structure benchmarked at scale rather than recited. No leetcode theater; assessment is building components later courses import (the ANN index is reused in AIE-302).',
    ethicsThread: 'Tier 1: algorithmic choices are measurable trade-offs. Tier 2: what ‘efficiency’ suppresses — approximate algorithms trade correctness for speed, and the error lands on whoever is hardest to retrieve. Tier 3: your ANN index will silently fail to find someone; who?',
    prereqNote: 'Prereq AIE-101 (Python fluency, testing). Co-req AIE-102 (the memory hierarchy — why cache-friendly layout matters). Learners write tested Python and understand memory cost. Every structure is built from scratch, tested, and benchmarked AT SCALE; the ANN index built here is imported by AIE-302 (RAG).',
    toolchain: 'Python 3.12+, NumPy for the vector/ANN work, pytest for correctness, and a benchmarking harness (time/memory at growing N). Big-O claims must be demonstrated with measured curves.',
    packets: [
      { id: 'AIE-110-M01', title: 'Complexity as a budget', hours: 10, focus: 'Big-O as a spending budget, not an exam trick: what breaks at 10^6, 10^9, 10^12 items. Amortized analysis (callback to AIE-102’s growable vector doubling). Measure a real curve and match it to its complexity class. Predict where a structure falls over.' },
      { id: 'AIE-110-M02', title: 'Arrays, hashing, and the structures under NumPy and dicts', hours: 14, focus: 'The structures under the ones you already use: contiguous arrays (why NumPy is fast — callback to AIE-102), hash tables (what a Python dict really is), collision handling, load factor. Build a hash table from scratch; benchmark against dict; predict collision behavior.' },
      { id: 'AIE-110-M03', title: 'Trees, heaps, and top-k at scale', hours: 14, focus: 'Trees, balanced trees, and heaps — with top-k (the operation retrieval and ranking actually need) as the driving problem. Build a heap; implement top-k two ways; benchmark. Predict which wins at large N vs small k before measuring.' },
      { id: 'AIE-110-M04', title: 'Graphs: traversal, shortest paths, PageRank intuition', hours: 14, focus: 'Graphs as the structure under knowledge, links, and relationships: representation, BFS/DFS, shortest paths, and PageRank intuition (eigenvector centrality, forward link to AIE-103 linear algebra). Build a graph and traverse it; predict traversal order and cost.' },
      { id: 'AIE-110-M05', title: 'Similarity search: exact to approximate nearest neighbors', hours: 16, focus: 'THE differentiator module: exact nearest-neighbor search, why it dies at scale, and approximate NN (LSH / HNSW intuition) as the trade of correctness for speed. Build an ANN index from scratch that AIE-302 (RAG) will import. Measure recall vs speed; predict the recall cliff.' },
      { id: 'AIE-110-M06', title: 'Streaming and sketching: counting when you can’t hold the data', hours: 12, focus: 'Counting and aggregating when the data does not fit in memory: streaming, reservoir sampling, and sketches (Bloom filter, HyperLogLog, Count-Min) as bounded-memory approximations. Build a Bloom filter and a HLL; predict the false-positive rate, then measure it.' },
    ],
  },
}

const course = COURSES[SELECTED]
if (!course) throw new Error(`unknown course: ${SELECTED}`)
const packets = course.packets
const DIR = `/home/user/CustomCourseBuilder/curriculum/ai-engineer/materials/${course.code}`

const PHILOSOPHY = `Binding curriculum philosophy — build to THIS, not textbook convention:
1. Descend, build, re-ascend: enter below the abstraction, build the thing at the substrate by hand, re-ascend to command the high-level tool.
2. Verification before generation: AI-PRIMM (Predict, Prompt, Read, Verify, Integrate) is the loop under every lab. Every lab states its Predict step (on paper, before code) before its Build step. A program that merely runs is never sufficient evidence — the artifact is the judgment trail.
3. Evaluation is a spine: every assessment must be gaming-resistant — a learner must not be able to pass without demonstrating the outcome. Grade the prediction and the reasoning, not just a passing program.
4. Ethics with teeth: the three-tier reading is specific to THIS module's subject — Tier 1 material ground (verifiable facts), Tier 2 what the field suppresses (what boosters can't say and critics idealize), Tier 3 "sit with this" (a QUESTION the learner cannot unknow, not a lecture).
5. The judgment trail is the credential: assessment measures judgment demonstrated, never content retained.`

const BAR = `THE QUALITY BAR (match this depth). The reference is AIE-102-M03 "The heap, manual memory, structs, and the segfault": 4 lessons each with teaching text + a worked example + named misconceptions; 3 labs each with explicit Predict (on paper, before code) / Build / Verify subsections and real starter+solution+test code; a gaming-resistant assessment graded on the judgment trail (predict, locate, fix, prove) not "it runs"; Elle pacing notes naming the walls, the reroutes, the accelerate conditions, and which struggle is productive vs blocked; and a subject-specific three-tier reading whose Tier 3 is a real question. Be concrete and technical — real code, real numbers, real worked examples. This is the material a learner actually uses, not an outline.`

const COURSE_CTX = `COURSE: ${course.code} — "${course.title}" (${course.tier} tier, durability ${course.durability}).
DESCENT ARC: ${course.descentArc}
WHAT OUTPACES THE FIELD: ${course.outpaces}
ETHICS THREAD (course-level): ${course.ethicsThread}
PREREQUISITE CONTEXT: ${course.prereqNote}
TOOLCHAIN: ${course.toolchain}`

const AUTHOR_SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['packetId', 'wrote', 'labCount', 'everyLabHasPredictStep'],
  properties: {
    packetId: { type: 'string' },
    wrote: { type: 'boolean', description: 'True if the full packet markdown was written to disk.' },
    labCount: { type: 'integer' },
    everyLabHasPredictStep: { type: 'boolean' },
    selfSummary: { type: 'string' },
  },
}

const GATE_SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['packetId', 'technical', 'evalDiscipline', 'ethics', 'coherence', 'overallPass', 'topFixes'],
  properties: {
    packetId: { type: 'string' },
    technical: { type: 'object', additionalProperties: false, required: ['pass', 'notes'], properties: { pass: { type: 'boolean' }, notes: { type: 'string' } } },
    evalDiscipline: { type: 'object', additionalProperties: false, required: ['pass', 'notes'], properties: { pass: { type: 'boolean' }, notes: { type: 'string' } } },
    ethics: { type: 'object', additionalProperties: false, required: ['pass', 'notes'], properties: { pass: { type: 'boolean' }, notes: { type: 'string' } } },
    coherence: { type: 'object', additionalProperties: false, required: ['pass', 'notes'], properties: { pass: { type: 'boolean' }, notes: { type: 'string' } } },
    overallPass: { type: 'boolean' },
    topFixes: { type: 'array', items: { type: 'string' } },
  },
}

log(`Dispatching ${course.code}: ${packets.length} packets → author (to ${DIR}) → four-gate`)

const results = await pipeline(
  packets,
  (p) => agent(
    `You are a senior curriculum engineer authoring one module of a first-party AI Engineer curriculum built to outpace every course on the internet.\n\n${COURSE_CTX}\n\n${PHILOSOPHY}\n\n${BAR}\n\nAUTHOR THIS PACKET IN FULL and WRITE it to ${DIR}/${p.id}.md using the Write tool:\n${p.id} — "${p.title}" (${p.hours} learner-hours)\nModule focus: ${p.focus}\n\nThe file must contain: a header, ## Lessons (each with teaching text, worked example, named misconceptions), ## Labs (each with explicit Predict / Build / Verify and real starter+solution+test code in fenced blocks), ## Assessment (with a gaming-resistant rubric table), ## Elle pacing notes, ## Three-tier reading. Match the M03 reference depth. All code must be correct under the stated toolchain. Write the complete file, then report.`,
    { label: `author:${p.id}`, phase: 'Author', schema: AUTHOR_SCHEMA, effort: 'high' }
  ).then((authored) =>
    agent(
      `You are an adversarial curriculum reviewer running the four quality gates on a just-written module packet. READ ${DIR}/${p.id}.md with the Read tool — that file is the source of truth, not any summary.\n\n${COURSE_CTX}\n\n${PHILOSOPHY}\n\n${BAR}\n\nPACKET: ${p.id} — "${p.title}". Author reported labCount=${authored?.labCount}, everyLabHasPredictStep=${authored?.everyLabHasPredictStep}.\n\nRun the four gates strictly. TECHNICAL: could a learner do every lab from the materials alone, and is every code answer-key correct under the toolchain? (Trace the code yourself.) EVAL-DISCIPLINE: is the assessment gaming-resistant, is Predict-before-Build real in every lab? ETHICS: is the three-tier reading subject-specific and is Tier 3 a real question? COHERENCE: does it honor the descent arc and resolve cross-module references? overallPass only if all four pass. Append a "## Gate report" section to the END of the file (use Edit/Write) recording each gate's pass/notes and any top fixes, then return the verdict.`,
      { label: `gate:${p.id}`, phase: 'Gate', schema: GATE_SCHEMA, effort: 'medium' }
    ).then((verdict) => ({ p, authored, verdict }))
  )
)

const clean = results.filter(Boolean)
const passed = clean.filter((r) => r.verdict?.overallPass)
log(`${course.code}: ${passed.length}/${clean.length} packets passed all four gates`)

return {
  course: course.code,
  summary: clean.map((r) => ({
    packetId: r.p.id, title: r.p.title,
    wrote: r.authored?.wrote ?? false, labCount: r.authored?.labCount ?? 0,
    overallPass: r.verdict?.overallPass ?? false,
    gates: { technical: r.verdict?.technical?.pass, evalDiscipline: r.verdict?.evalDiscipline?.pass, ethics: r.verdict?.ethics?.pass, coherence: r.verdict?.coherence?.pass },
    topFixes: r.verdict?.topFixes ?? [],
  })),
}
